### testing send a message through the API
POST http://localhost:8080/api/whatsapp/message
Content-Type: application/json
Accept: application/json

{
    "to": "+59160676400",
    "body": "Hola Alex, este es un mensaje de prueba"
}



####
POST http://localhost:8080/api/whatsapp/message/template
Content-Type: application/json
Accept: application/json

{
    "to": "+59174845900",
    "body": "probando :D",
    "date": "2021-09-30T00:00:00.000Z",
    "time": "12:00:00"
}

### GET
GET http://localhost:8080/api/whatsapp/message/MM92e9d073da19ff60894a6f4eb4f19b83
Content-Type: application/json
Accept: application/json
