
####
POST https://graph.facebook.com/v22.0/564075936794992/messages
Authorization: Bearer EAAJhNx9BSi8BO2oVtmhZCQdVWwbSA0X27U0fZAS3C7dqSHJjTMaR2ZCl5luPKZBvwxVnZC8N4y762oWeOBPsr437YskbbNtyUmawzqrhLzNt9QL2ZAcZAEDtlLnKLyGBmVrjiCJPd3dJp4ZAsMeoP5LiHxh18toZC7WU3ZBOZBFtLBLRt7ZBMh2GcuTpmBOljPrVBFgyTOOuk1saFMJS4r8wwtnVuetvpMsZD
Content-Type: application/json

{
  "messaging_product": "whatsapp",
  "to": "59174845900",
  "type": "template",
  "template": {
    "name": "notification",
    "language": {
      "code": "es_MX"
    },
    "components": [
      {
        "type": "body",
        "parameters": [
          {
            "type": "text",
            "text": "2025-03-11"
          },
          {
            "type": "text",
            "text": "14:30"
          }
        ]
      }
    ]
  }
}


### testing a post send message
POST http://localhost:8080/api/whatsapp/message
Content-Type: application/json
Accept: application/json

{
  "to": "59174845900",
  "date": "2025-03-11",
  "time": "14:30"
}
